# Generated by Django 5.0.1 on 2025-11-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('rider', 'Rider'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
